name: compound
description: A Flutter app that utilizes most Firebase Services.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # state management
  stacked: ^1.7.2
  # third-party services
  stacked_services: ^0.4.4+3
  # navigation
  auto_route: ^0.6.1
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  # loading animations
  flutter_spinkit: ^4.1.2+1
  # logger
  logger: ^0.9.1
  # image picker
  image_picker: ^0.6.7+4
  # cached network image
  cached_network_image: ^2.2.0+1

  # Firebase Related Stuff
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.16
  firebase_dynamic_links: ^0.5.1
  firebase_remote_config: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  auto_route_generator: ^0.6.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
